name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install modules
        run: npm ci
      - name: Create package tarball
        run: |
          npm pack
          PACKAGE_FILE="$(ls *.tgz | head -n 1)"
          cp "$PACKAGE_FILE" emftosvg.tgz
      - name: Create Release and upload tarball
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tgz'
          overwrite_files: true
          draft: false
          prerelease: false
